backend:
  name: git-gateway
  branch: main
media_folder: "assets/images"
public_folder: "/images"
collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Large Image", name: "imageLarge", widget: "image"}
      - {label: "Before Image", name: "beforeImage", widget: "image"}
      - {label: "After Image", name: "afterImage", widget: "image"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["kitchen", "bathroom", "floor"]}
      - {label: "Video", name: "video", widget: "file", required: false}
  - name: "reviews"
    label: "Reviews"
    folder: "reviews"
    create: true
    fields:
      - {label: "Quote", name: "quote", widget: "text"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Video", name: "video", widget: "file", required: false}
      - {label: "Video Poster", name: "poster", widget: "image", required: false}
